/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2015
 * 
 * XDoclet definition:
 * @struts.form name="assessItemForm"
 */
public class AssessItemForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String assessId;
	private String assessName;
	private short percentage;
	private String[] teacherType;
	
	
	
	public String getAssessId() {
		return assessId;
	}
	public void setAssessId(String assessId) {
		this.assessId = assessId;
	}
	public String getAssessName() {
		return assessName;
	}
	public void setAssessName(String assessName) {
		this.assessName = assessName;
	}
	
	public short getPercentage() {
		return percentage;
	}
	public void setPercentage(short percentage) {
		this.percentage = percentage;
	}
	public String[] getTeacherType() {
		return teacherType;
	}
	public void setTeacherType(String[] teacherType) {
		this.teacherType = teacherType;
	}
	
	
}