/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-04-2014
 * 
 * XDoclet definition:
 * @struts.form name="choosePreTimeForm"
 */
public class ChoosePreTimeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** timeslot property */
	private String timeslot;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the timeslot.
	 * @return String
	 */
	public String getTimeslot() {
		return timeslot;
	}

	/** 
	 * Set the timeslot.
	 * @param timeslot The timeslot to set
	 */
	public void setTimeslot(String timeslot) {
		this.timeslot = timeslot;
	}
}