/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 03-12-2015
 * 
 * XDoclet definition:
 * @struts.form name="fileUploadForm"
 */
public class FileUploadForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer flag2;
	private FormFile excelFile;
	
	public Integer getFlag2() {
		return flag2;
	}
	public void setFlag2(Integer flag2) {
		this.flag2 = flag2;
	}
	public FormFile getExcelFile() {
		return excelFile;
	}
	public void setExcelFile(FormFile excelFile) {
		this.excelFile = excelFile;
	}
	
}