/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-16-2015
 * 
 * XDoclet definition:
 * @struts.form name="gradeLevelForm"
 */
public class GradeLevelForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String[] GradeLevel_id;
	private String[] GradeLevel_percent;
	public String[] getGradeLevel_id() {
		return GradeLevel_id;
	}
	public void setGradeLevel_id(String[] gradeLevel_id) {
		GradeLevel_id = gradeLevel_id;
	}
	public String[] getGradeLevel_percent() {
		return GradeLevel_percent;
	}
	public void setGradeLevel_percent(String[] gradeLevel_percent) {
		GradeLevel_percent = gradeLevel_percent;
	}
	
}