/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-29-2014
 * 
 * XDoclet definition:
 * @struts.form name="observerForm"
 */
public class ObserverForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** obsTopic property */
	private String[] obsTopic;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the obsTopic.
	 * @return String
	 */
	public String[] getObsTopic() {
		return obsTopic;
	}

	/** 
	 * Set the obsTopic.
	 * @param obsTopic The obsTopic to set
	 */
	public void setObsTopic(String[] obsTopic) {
		this.obsTopic = obsTopic;
	}
}