/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-15-2014
 * 
 * XDoclet definition:
 * @struts.form name="selectTopicForm"
 */
public class SelectTopicForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** teamMenber property */
	private String teamMenber;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the teamMenber.
	 * @return String
	 */
	public String getTeamMenber() {
		return teamMenber;
	}

	/** 
	 * Set the teamMenber.
	 * @param teamMenber The teamMenber to set
	 */
	public void setTeamMenber(String teamMenber) {
		this.teamMenber = teamMenber;
	}
}