/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2014
 * 
 * XDoclet definition:
 * @struts.form name="uploadFYPForm"
 */
public class UploadFYPForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** numOfStu property */
	private String numOfStu;

	/** title property */
	private String title;

	/** individual property */
	private String individual;

	/** supervisor property */
	private String[] supervisor;

	/** description property */
	private String description;

	/** credit property */
	private String credit;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the numOfStu.
	 * @return String
	 */
	public String getNumOfStu() {
		return numOfStu;
	}

	/** 
	 * Set the numOfStu.
	 * @param numOfStu The numOfStu to set
	 */
	public void setNumOfStu(String numOfStu) {
		this.numOfStu = numOfStu;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the individual.
	 * @return String
	 */
	public String getIndividual() {
		return individual;
	}

	/** 
	 * Set the individual.
	 * @param individual The individual to set
	 */
	public void setIndividual(String individual) {
		this.individual = individual;
	}

	/** 
	 * Returns the supervisor.
	 * @return String
	 */
	public String[] getSupervisor() {
		return supervisor;
	}

	/** 
	 * Set the supervisor.
	 * @param supervisor The supervisor to set
	 */
	public void setSupervisor(String[] supervisor) {
		this.supervisor = supervisor;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription() {
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Returns the credit.
	 * @return String
	 */
	public String getCredit() {
		return credit;
	}

	/** 
	 * Set the credit.
	 * @param credit The credit to set
	 */
	public void setCredit(String credit) {
		this.credit = credit;
	}
}