/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-22-2014
 * 
 * XDoclet definition:
 * @struts.form name="workloadForm"
 */
public class WorkloadForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String[] workload;

	public String[] getWorkload() {
		return workload;
	}

	public void setWorkload(String[] workload) {
		this.workload = workload;
	}
}