/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.domain.Coordinator;
import com.uic.domain.Student;
import com.uic.domain.Teacher;
import com.uic.service.imp.StudentServiceImp;
import com.uic.service.imp.UsersServiceImp;
import com.uic.service.inter.StudentServiceInter;
import com.uic.service.inter.UsersServiceInter;
import com.uic.web.struts.form.ChangePwdForm;

/**
 * MyEclipse Struts Creation date: 10-30-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag"
 */
public class ChangPwdAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward teacherChangePwdUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//System.out.println("Using TeacherPageControlAction");
		if(request.getSession().getAttribute("role").equals("teacher")){
			return mapping.findForward("goTeacherPwdUi");
		}else{
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
	
	public ActionForward goPwdUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("coordinator")) {
			return mapping.findForward("goPwdUi");
		}else if(request.getSession().getAttribute("role").equals("student")){
			StudentServiceInter studentService = new StudentServiceImp();
			Student stu = (Student)request.getSession().getAttribute("studentinfo");
			Student s = studentService.getStudentById(stu.getSid());
			request.setAttribute("telephone", s.getTelephone());
			return mapping.findForward("goStudentChangePwdUi");
		}else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
	
	public ActionForward updateTelephone(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String role = (String) request.getSession().getAttribute("role");
		if (role.equals("student")) {
			/*
			 * 1.get telephone number from web page
			 */
			String telephone = request.getParameter("telephone");
			//System.out.println(telephone);
			/*
			 * 2. validate the telephone
			 */
			Map<String, String> errors = validateTelephone(telephone);
			//System.out.println(errors.size());
			if(errors.size()>0){
				request.setAttribute("telephone", telephone);
				request.setAttribute("errors", errors);
				//return mapping.findForward("goStudentChangePwdUi");
				return new ActionForward("/changPwd.do?flag=goPwdUi");
			}
			/*
			 * 3. use studentService to complete
			 */
			StudentServiceInter studentService = new StudentServiceImp();
			Student stu = (Student)request.getSession().getAttribute("studentinfo");
			if(studentService.updateTelephone(stu.getId()+"", telephone)){
				//success
				request.setAttribute("updateTelephoneState", "success");
			}else{
				request.setAttribute("updateTelephoneState", "failed");
			}
			/*
			 * 4. return
			 */
			//return mapping.findForward("goStudentChangePwdUi");
			return new ActionForward("/changPwd.do?flag=goPwdUi");
			
		}else{
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}

	public ActionForward changePwd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ChangePwdForm changePwdForm = (ChangePwdForm) form;
		String role = (String) request.getSession().getAttribute("role");

		String oldPwd = changePwdForm.getOldPwd();
		String newPwd = changePwdForm.getNewPwd();

		if (role.equals("coordinator")) {

			Coordinator coordinator = (Coordinator) request.getSession()
					.getAttribute("coordinatorinfo");
			if (oldPwd.equals(coordinator.getPassword())) {
				if (oldPwd.equals(newPwd)) {
					request.setAttribute(
							"PwdError",
							"Your new password can't be the same as the original password. Please try again!");
					return mapping.findForward("goPwdUi");
				} else {
					UsersServiceInter usersServiceInter = new UsersServiceImp();
					if (usersServiceInter.changePwd(role, newPwd,
							coordinator.getId() + "")) {
						request.setAttribute("msg", "Your password has changed. Please login again!");
						return mapping.findForward("goLogin");
					} else {
						request.setAttribute("PwdError",
								"Change password error!");
						return mapping.findForward("goPwdUi");
					}
				}
			} else {
				request.setAttribute("PwdError",
						"Your original password error!");
				return mapping.findForward("goPwdUi");
				
			}

		} 
		else if(role.equals("teacher")){
			Teacher teacher = (Teacher)request.getSession().getAttribute("teacherinfo");
			if (oldPwd.equals(teacher.getPassword())) {
				if (oldPwd.equals(newPwd)) {
					request.setAttribute(
							"PwdError",
							"Your new password can't be the same as the original password. Please try again!");
					return mapping.findForward("goTeacherPwdUi");
				} else {
					UsersServiceInter usersServiceInter = new UsersServiceImp();
					if (usersServiceInter.changePwd(role, newPwd,
							teacher.getId() + "")) {
						request.setAttribute("msg", "Your password has changed. Please login again!");
						return mapping.findForward("goLogin");
					} else {
						request.setAttribute("PwdError",
								"Change password error!");
						return mapping.findForward("goTeacherPwdUi");
					}
				}
			}else {
				request.setAttribute("PwdError",
						"Your original password error!");
				return mapping.findForward("goTeacherPwdUi");
				
			}
		}else if(role.equals("student")){
			Student student = (Student)request.getSession().getAttribute("studentinfo");
			if (oldPwd.equals(student.getPassword())) {
				if (oldPwd.equals(newPwd)) {
					request.setAttribute(
							"PwdError",
							"Your new password can't be the same as the original password. Please try again!");
					return mapping.findForward("goStudentPwdUi");
				} else {
					UsersServiceInter usersServiceInter = new UsersServiceImp();
					if (usersServiceInter.changePwd(role, newPwd,
							student.getId() + "")) {
						request.setAttribute("msg", "Your password has changed. Please login again!");
						return mapping.findForward("goLogin");
					} else {
						request.setAttribute("PwdError",
								"Change password error!");
						return mapping.findForward("goStudentChangePwdUi");
					}
				}
			}else {
				request.setAttribute("PwdError",
						"Your original password error!");
				return mapping.findForward("goStudentChangePwdUi");
				
			}
		}
		
		else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
	
	private Map<String, String> validateTelephone(String telephone){
		Map<String, String> errors = new HashMap<String, String>();
		if(telephone == null || telephone.trim().isEmpty()){
			errors.put("telephone", "Mobile phone number is required!");
			//System.out.println("Empty");
		}else if(!telephone.matches("^0?1[3|4|5|8][0-9]\\d{8}$")){
			errors.put("telephone", "Your mobile phone number is incorrect,  please enter your phone number in the correct format.");
			//System.out.println("format error");
		}
		return errors;
	}
}
