/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.domain.Teacher;
import com.uic.service.imp.ChangePwdServiceImp;
import com.uic.web.struts.form.ChangePwdForm;

/**
 * MyEclipse Struts Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/changePwd" name="changePwdForm"
 *                input="/WEB-INF/logined/Teacher/changePwd.jsp"
 *                parameter="flag" scope="request" validate="true"
 * @struts.action-forward name="teacherChangePwd"
 *                        path="/WEB-INF/logined/Teacher/changePwd.jsp"
 */
public class ChangePwdAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward teacherChangePwd(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		ChangePwdForm changePwdForm = (ChangePwdForm) form;// TODO
															// Auto-generated
															// method stub
		HttpSession s=request.getSession();
		Teacher teacher=(Teacher) s.getAttribute("teacherinfo");
		String oldPwd=teacher.getPassword();
		System.out.println(teacher.getName()+teacher.getPassword()+teacher.getId()+teacher.getAccount());
		System.out.println("password:"+changePwdForm.getNewPwd()+" "+changePwdForm.getOldPwd());
		if(oldPwd.equals(changePwdForm.getOldPwd())){
			//change new password
			ChangePwdServiceImp service= new ChangePwdServiceImp();
			
			service.changePwd(teacher.getId().toString(), changePwdForm.getNewPwd());
			System.out.println("pwd changed!");
			return mapping.findForward("changePwdOk");
		}else{
			//return to the page
			return mapping.findForward("changePwdErr");
		}
		
	}
}