/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.domain.Time;
import com.uic.service.inter.TimeType;
import com.uic.util.TimeChecker;


/**
 * MyEclipse Struts Creation date: 10-29-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag"
 */
public class ExportAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward goExportUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("coordinator")) {
			
			//check time whether student has finished the presentation choose
			Time checker = TimeChecker.timeCheck();
			if(checker.getType().equals(TimeType.system_done)){
				//can export presentation timetable
				request.setAttribute("TimetableState", "true");
				
				
			}else{
				request.setAttribute("TimetableState", "false");
			}
			

			
			return mapping.findForward("goExportUi");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
}