/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.domain.AssessItem;
import com.uic.domain.StuTopic;
import com.uic.domain.Student;
import com.uic.domain.StudentGrade;
import com.uic.domain.Teacher;
import com.uic.service.imp.AssessItemServiceImp;
import com.uic.service.imp.FYPServiceImp;
import com.uic.service.imp.GradeLevelServiceImp;
import com.uic.service.imp.StudentServiceImp;
import com.uic.service.imp.TeachersServiceImp;
import com.uic.service.inter.AssessItemServiceInter;
import com.uic.service.inter.FYPServiceInter;
import com.uic.service.inter.GradeLevelServiceInter;
import com.uic.service.inter.StudentServiceInter;
import com.uic.service.inter.TeachersServiceInter;

/**
 * MyEclipse Struts Creation date: 05-20-2015
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag" validate="true"
 * @struts.action-forward name="Grading"
 *                        path="/WEB-INF/logined/Teacher/Grading.jsp"
 */
public class GradingAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward goGradingUI(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("teacher")) {
			Teacher teacher = (Teacher) request.getSession().getAttribute("teacherinfo");
			FYPServiceInter fypService = new FYPServiceImp();
			TeachersServiceInter teacherService = new TeachersServiceImp();
			GradeLevelServiceInter gradeLevelService = new GradeLevelServiceImp();
			
			
			ArrayList<Student> ss = teacherService.getSuperviseStudentList(teacher.getId().toString());
			ArrayList<Student> os = teacherService.getObservateStudentList(teacher.getId().toString());
			ArrayList<Student> es = teacherService.getExmineStudentList(teacher.getId().toString());
			ArrayList<StuTopic> sst = new ArrayList<StuTopic>();
			ArrayList<StuTopic> ost = new ArrayList<StuTopic>();
			ArrayList<StuTopic> est = new ArrayList<StuTopic>();
			HashMap<String,StudentGrade> studentGrade = new HashMap<String,StudentGrade>();
			for (Student s : ss) {
				List<StuTopic> st = fypService.getStuTopicByStudent(s);
				sst.add(st.get(0));
				if(gradeLevelService.getStudentGrade(s.getId().toString()).size()==0){
					studentGrade.put(s.getName(), null);
				}else{
					studentGrade.put(s.getName(), gradeLevelService.getStudentGrade(s.getId().toString()).get(0));
				}
				
			}
			for (Student s : os) {
				List<StuTopic> st = fypService.getStuTopicByStudent(s);
				ost.add(st.get(0));
				if(gradeLevelService.getStudentGrade(s.getId().toString()).size()==0){
					studentGrade.put(s.getName(), null);
				}else{
					studentGrade.put(s.getName(), gradeLevelService.getStudentGrade(s.getId().toString()).get(0));
				}
			}
			for (Student s : es) {
				List<StuTopic> st = fypService.getStuTopicByStudent(s);
				est.add(st.get(0));
				if(gradeLevelService.getStudentGrade(s.getId().toString()).size()==0){
					studentGrade.put(s.getName(), null);
				}else{
					studentGrade.put(s.getName(), gradeLevelService.getStudentGrade(s.getId().toString()).get(0));
				}
			}

			request.setAttribute("superviseStudentTopicList", sst);
			request.setAttribute("observateStudentTopicList", ost);
			request.setAttribute("examineStudentTopicList", est);
			request.setAttribute("studentGrade", studentGrade);
			return mapping.findForward("gradingUI");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}

	public ActionForward goEditGradeUI(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("teacher")) {
			String studentID = request.getParameter("sid");
			AssessItemServiceInter assessItemService = new AssessItemServiceImp();
			GradeLevelServiceInter gradeService = new GradeLevelServiceImp();
			StudentServiceInter studentService = new StudentServiceImp();

			List<AssessItem> assessItemslist = assessItemService.getAssessItems();
			Student curStudent = studentService.getStudentById(studentID);
			List<StudentGrade> sg = gradeService.getStudentGrade(curStudent.getId().toString());
			if (sg.size() == 0) {
				request.setAttribute("record", "noRecord");
				System.out.println("No record");
			} else {
				request.setAttribute("record", "hasRecord");
				HashMap<String, String> sgMap = getScore(sg.get(0).getGrade());
				request.setAttribute("grade", sgMap);
				System.out.println("Has record");
			}
			request.setAttribute("assementItemList", assessItemslist);
			request.setAttribute("curStudent", curStudent);
			return mapping.findForward("editGradeUI");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}

	public ActionForward editGrade(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("teacher")) {
			AssessItemServiceInter assessItemService = new AssessItemServiceImp();
			StudentServiceInter studentService = new StudentServiceImp();
			GradeLevelServiceInter gradeLevelService = new GradeLevelServiceImp();

			List<AssessItem> assessItemslist = assessItemService.getAssessItems();
			String studentID = request.getParameter("studentID");
			Student student = studentService.getStudentById(studentID);
			List<StudentGrade> studentGradeList = gradeLevelService.getStudentGrade(student.getId().toString());
			String gradeList = new String();
			System.out.println("studentGradeList.size()"+studentGradeList.size());
			if (studentGradeList.size() == 0) {
				for (AssessItem assessItem : assessItemslist) {
					gradeList = codeScore(assessItem.getName(), request.getParameter(assessItem.getName()), gradeList);
				}
				StudentGrade sg = new StudentGrade();
				sg.setGrade(gradeList);
				sg.setStudent(student);
				sg.setTotalScore(calculateTotalScore(gradeList,assessItemslist));
				// save sg
				gradeLevelService.saveStudentGrade(sg);
				request.setAttribute("gradeSavedSuccess", "true");
				request.setAttribute("gradeSavedSuccessInfo", student.getName()+"'s grade saved.");
				return mapping.findForward("goGrading");
			}else{
				for (AssessItem assessItem : assessItemslist) {
					gradeList = codeScore(assessItem.getName(), request.getParameter(assessItem.getName()), gradeList);
				}
				
				// update sg
				gradeLevelService.updateStudentGrade(gradeList,calculateTotalScore(gradeList,assessItemslist),student.getId().toString());
				request.setAttribute("gradeSavedSuccess", "true");
				request.setAttribute("gradeSavedSuccessInfo", student.getName()+"'s grade updated.");
				return mapping.findForward("goGrading");
			}
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}

	public HashMap<String, String> getScore(String gradeList) {
		HashMap<String, String> map = new HashMap<String, String>();
		String[] grades = gradeList.split(";");
		for (String grade : grades) {
			String[] g = grade.split(",");
			map.put(g[0], g[1]);
		}
		return map;
	}

	public String calculateTotalScore(String gradeList, List<AssessItem> assessItemsList){
		//算总分公式
		HashMap<String, String> score = getScore(gradeList);
		HashMap<String, String> scoreMap = getScoreMap();
		float totalScore = 0;
		System.out.println("initial total score:"+totalScore);
		for(AssessItem assessItem: assessItemsList){
			totalScore = totalScore + Float.parseFloat(scoreMap.get(score.get(assessItem.getName()))) * assessItem.getPercent()/100;
			System.out.println("next total score " +assessItem.getName()+":"+totalScore);
		}
		java.text.DecimalFormat df = new java.text.DecimalFormat("#0.00");
        String total = df.format(totalScore);
		return total;
	}
	
	public HashMap<String,String> getScoreMap(){
		HashMap<String, String> scoreMap = new HashMap<String, String>();
		scoreMap.put("A", "4.00");
		scoreMap.put("A-", "3.67");
		scoreMap.put("B+", "3.33");
		scoreMap.put("B", "3.00");
		scoreMap.put("B-", "2.67");
		scoreMap.put("C+", "2.33");
		scoreMap.put("C", "2.00");
		scoreMap.put("C-", "1.67");
		scoreMap.put("D", "1");
		scoreMap.put("F", "0");
		return scoreMap;
	}
	
	
	public String codeScore(String name, String grade, String gradeList) {
		gradeList = gradeList + name + "," + grade + ";";
		return gradeList;
	}

}