/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.util.BaseUtil;
import com.uic.util.PropertiesHelper;
import com.uic.web.struts.form.PreTimeForm;

/**
 * MyEclipse Struts Creation date: 10-31-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag"
 */
public class PreTimeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward goPreTimeUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("coordinator")) {

			return mapping.findForward("goPreTimeUi");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
	
	public ActionForward setPreTime(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if (request.getSession().getAttribute("role").equals("coordinator")) {
			PreTimeForm preTimeForm = (PreTimeForm)form;
			
			String startDate = preTimeForm.getStartDate();
			String startTime = preTimeForm.getStartTime();
			String endDate = preTimeForm.getEndDate();
			String endTime = preTimeForm.getEndTime();
			
			String startDateTime = startDate+" "+startTime;
			String endDateTime = endDate+" "+endTime;
			
			System.out.println(startDateTime);
			System.out.println(endDateTime);
			
			java.util.Date dStartTime = BaseUtil.StringConvertDate(startDateTime);
			java.util.Date dEndTime = BaseUtil.StringConvertDate(endDateTime);
			
			java.util.Date nowDate = new java.util.Date();
			
			
			if(dStartTime.after(nowDate)&&dEndTime.after(nowDate)&&dStartTime.before(dEndTime)){
				PropertiesHelper ph = new PropertiesHelper("/WEB-INF/config/FYP-system.properties");
				
				try {
					ph.setProperties("PreStartDateTime", startDateTime);
					ph.setProperties("PreEndDateTime", endDateTime);
					ph.setProperties("PreDateTimeState", "true");
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				request.setAttribute("PreTimeOperation", "success");
			}else{
				request.setAttribute("PreTimeOperation", "error");
			}
			
			return mapping.findForward("goPreTimeUi");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
}