/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uic.service.imp.TeachersServiceImp;
import com.uic.service.inter.TeachersServiceInter;
import com.uic.web.struts.form.WorkloadForm;


/** 
 * MyEclipse Struts
 * Creation date: 11-22-2014
 * 
 * XDoclet definition:
 * @struts.action path="/setWorkload" name="workloadForm" parameter="flag" scope="request"
 */
public class SetWorkloadAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward goUi(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if (request.getSession().getAttribute("role").equals("coordinator")) {
			//ready teacher info for quota.jsp
			TeachersServiceInter teachersServiceInter =  new TeachersServiceImp();
			request.setAttribute("teacherList", teachersServiceInter.getTeachers());
			
			return mapping.findForward("goWorkloadUi");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}	
	}
	
	public ActionForward saveWorkload(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if (request.getSession().getAttribute("role").equals("coordinator")) {
			WorkloadForm workloadForm = (WorkloadForm)form;
			
			String[] workload = workloadForm.getWorkload();
			boolean flag = true;
			
			TeachersServiceInter teachersServiceInter = new TeachersServiceImp();
			
			for(int i=0;i<workload.length;i++){
				String[] temp = workload[i].split(",");
				try {
					teachersServiceInter.saveWorkload(temp[0], temp[1]);
				} catch (Exception e) {
					// TODO: handle exception
					flag=false;
					break;
				}
			}
			
			if(flag){
				request.setAttribute("SaveWorkloadOperation", "success");
			}else{
				request.setAttribute("SaveWorkloadOperation", "error");
			}
			
			//ready teacher info for quota.jsp
			return new ActionForward("/setWorkload.do?flag=goUi");
		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}	
	}
}