/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.uic.web.struts.form.SelectTopicForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-15-2014
 * 
 * XDoclet definition:
 * @struts.action path="/stuSelectTopic" name="selectTopicForm" parameter="flag" scope="request" validate="true"
 * @struts.action-forward name="chooseGroupTopic" path="/WEB-INF/logined/Student/teamTopicSelection.jsp"
 */
public class StuSelectTopicAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SelectTopicForm selectTopicForm = (SelectTopicForm) form;// TODO Auto-generated method stub
		return null;
	}
}