/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uic.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.uic.web.struts.form.TimeslotForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-30-2014
 * 
 * XDoclet definition:
 * @struts.action path="/timetable" name="timeslotForm" parameter="flag" scope="request" validate="true"
 */
public class TimetableAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TimeslotForm timeslotForm = (TimeslotForm) form;// TODO Auto-generated method stub
		
		String[] timeslots= timeslotForm.getTimeslot();
		for(int i = 0;i<timeslots.length;i++){
			System.out.println(timeslots[i]);
		}
		return null;
	}
}